apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kouxi-blog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/kouxi-blog
    repoURL: https://github.com/kouxi08/astro_blog.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

